### ISSUE TITLE
Update to latest version of docfx

### ISSUE THREAD

**Issue by sorvis** [tsgkdt/docker-docfx#1]
Hello,

Would it be possible to update this to the latest version of docfx? Also I noticed that docfx was complaining about not having git installed would that make sense to add to the image?

**Comment by tsgkdt** [comment]
@sorvis 

Thank you for your feedback.
I updated this to the latest version of docfx.
Also, I added git command in docker image.

please confirm it.

**Comment by sorvis** [comment]
@tsgkdt  thank you! It appears to be working.
