### ISSUE TITLE
cant find `docfx.json` when running example

### ISSUE THREAD

**Issue by AaronLayton** [tsgkdt/docker-docfx#3]
Hi @tsgkdt 

I am trying to run 

`docker run --rm -it tsgkadot/docker-docfx:latest docfx build` inside my project folder that contains a `docfx.json` file but I get the following errors

```
λ docker run -it tsgkadot/docker-docfx:latest docfx build
[19-03-07 04:19:12.784]Error:Either provide config file or specify content files to start building documentation.
```

am I right in thinking I need to copy my files _into_ the docker image? or should it have access to my local file system to read the files it needs?

**Comment by tsgkdt** [comment]
>  should it have access to my local file system to read the files it needs?
Yes. I think so. Using volume mount option,  any files don't need to copy into the docker image.

For example, docfx project exists in /home/testuser/docfx_project.
Run command should be...
> docker run --rm -it -v  /home/testuser/docfx_project:/tmp  tsgkadot/docker-docfx:latest docfx /tmp/docfx.json

And, when build is finished, html files are created in _site directory.

If you have further question, please let me know.
Thanks for the feedback.

**Comment by AaronLayton** [comment]
Perfect! Thanks @tsgkdt - sorry still pretty new to Docker

Maybe add a line in the readme.md for your above example? It worked perfectly in my pipelines though ;-)
